[profile.default]
src  = 'src'
test = 'tests/forge'
out  = 'forge_out'
libs = ['lib']
remappings = [
    '@solmate=lib/solmate/src/',
    '@std=lib/forge-std/src/',
    '@clones=lib/clones-with-immutable-args/src/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@prb-math=lib/prb-math/',
    '@base64-sol=lib/base64/',
    'src/=src/'
]
verbosity           = 2
block_timestamp     = 1_672_372_127
block_number        = 16_295_000
fork_block_number   = 16_295_000
rpc_storage_caching = { chains = ["mainnet"], endpoints = "all" }
optimizer           = true
optimizer_runs      = 0
fs_permissions      = [{ access = "read-write", path = "./"}]
# libraries = [
#     'src/libraries/external/BorrowerActions.sol:BorrowerActions:0x422d470fb02206733Bb770D2A27d6d98f493af64',
#     'src/libraries/external/KickerActions.sol:KickerActions:0xf419056B545783BbFfEAB4d0aA057a52FbA4F4fd',
#     'src/libraries/external/LPActions.sol:LPActions:0xb257A98a3549a0B36b9001d0eDc9e75d313d5c8e',
#     'src/libraries/external/LenderActions.sol:LenderActions:0x7456CF19C121842FE2C3a888075A11d51ED63b98',
#     'src/libraries/external/PoolCommons.sol:PoolCommons:0xe77bfEeB83CD09bD9b598a90f7Ce7faE02c71540',
#     'src/libraries/external/PositionNFTSVG.sol:PostionNFTSVG:0x701ea8F0825E7B160c8C39160783eB45f8110424',
#     'src/libraries/external/SettlerActions.sol:SettlerActions:0x9EdcD1fEc19E5baA98fa4911C90C2162524750d2',
#     'src/libraries/external/TakerActions.sol:TakerActions:0xb127207d673977e14f31f52a14AD07e6a512c5fA'
# ]
libraries = [
    'src/libraries/external/BorrowerActions.sol:BorrowerActions:0xcfe2f2C9652365Ae4854906423c229D3A42a3C6a',
    'src/libraries/external/KickerActions.sol:KickerActions:0xb052909362e54420Af97dCb5961EFc803Dd0ec6D',
    'src/libraries/external/LPActions.sol:LPActions:0x355ba510B1A5F68a7e06D9FD5D86E36b9345bddB',
    'src/libraries/external/LenderActions.sol:LenderActions:0xFf08C829dAE8474018E207b92a0135FF0dc54ACF',
    'src/libraries/external/PoolCommons.sol:PoolCommons:0xB80c6f3674d9b1E542eEc30cf2a3F954da899212',
    'src/libraries/external/PositionNFTSVG.sol:PostionNFTSVG:0xf712Ff55c70e9C12D39177256ced13F363100402',
    'src/libraries/external/SettlerActions.sol:SettlerActions:0xF204Ee2f36E5f6A13135e62ae7FA8d5931459De2',
    'src/libraries/external/TakerActions.sol:TakerActions:0x97fd1D11BE945f4c3b4976F8865abf604dBDC1EB'
]
# for some reason etherscan would fail to verify ERC20/721Pool w/o paris specified, leaving it on make cannon generated different bytecode oof
evm_version = 'paris'
[fuzz]
runs = 300

[invariant]
runs           = 1000   # Number of times that a sequence of function calls is generated and run
depth          = 20     # Number of function calls made in a given run.
call_override  = false  # Override calls
fail_on_revert = true   # Fail the test if the contract reverts